name: qinhuai
description: A sample command-line application.
version: 1.0.0
homepage: https://www.example.com

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.0.5
  meta: ^1.8.0
  path_provider: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.3
  isar_generator: ^3.0.5
  lints: ^2.0.0
  test: ^1.16.0
