name: flutter_beacons
description: The Dart side of beacons.
version: 1.0.0
repository: https://github.com/Parkour-Labs/beacons/

environment:
  sdk: ^3.1.0

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
