[package]
name = "beacons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
beacons_macros = { path = "../beacons_macros" }
derive_more = "0.99.17"
postcard = { version = "1.0.4", features = [ "alloc" ] }
rand = "0.8.5"
rusqlite = "0.29.0"
serde = { version = "1.0.164", features = [ "derive" ] }
serde_json = "1.0.99"
