name: flutter_beacons_generator
description: Code generator for the Dart side of beacons.
version: 1.0.0
repository: https://github.com/Parkour-Labs/beacons/
publish_to: "none"

environment:
  sdk: ^3.1.0

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  build_config: ^1.1.1
  flutter_beacons:
    path: ../flutter_beacons
  source_gen: ^1.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
