name: example
description: A sample command-line application.
version: 1.0.0
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dust:
    path: ../../

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  dust_generator:
    path: ../
  build_runner: ^2.4.8
